-- FolioLens MVP logical schema
-- Source: docs/API_명세서.md, docs/기능명세서.md, docs/요구사항_정의서.md
-- Target: PostgreSQL
--
-- This file creates structure only. UUID values are generated by the application
-- so the schema does not require a PostgreSQL extension.

SET search_path TO public;

CREATE TABLE disclosure_types (
    code                 VARCHAR(64) PRIMARY KEY,
    display_name         VARCHAR(100) NOT NULL,
    supported            BOOLEAN NOT NULL DEFAULT TRUE,
    description          TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE owners (
    id                   UUID PRIMARY KEY,
    owner_kind           VARCHAR(20) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT ck_owners_kind
        CHECK (owner_kind IN ('DEMO_SESSION', 'USER')),
    CONSTRAINT ck_owners_status
        CHECK (status IN ('ACTIVE', 'EXPIRED', 'DELETED'))
);

CREATE TABLE demo_sessions (
    id                   UUID PRIMARY KEY,
    owner_id             UUID NOT NULL,
    token_hash           CHAR(64) NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    last_accessed_at     TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at           TIMESTAMPTZ,
    CONSTRAINT uq_demo_sessions_owner UNIQUE (owner_id),
    CONSTRAINT uq_demo_sessions_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_demo_sessions_owner
        FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE,
    CONSTRAINT ck_demo_sessions_expiry
        CHECK (expires_at > created_at)
);

CREATE TABLE portfolios (
    id                      UUID PRIMARY KEY,
    owner_id                UUID NOT NULL,
    name                    VARCHAR(50) NOT NULL,
    description             VARCHAR(500),
    analysis_input_version  BIGINT NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT fk_portfolios_owner
        FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE,
    CONSTRAINT ck_portfolios_name
        CHECK (char_length(btrim(name)) BETWEEN 1 AND 50),
    CONSTRAINT ck_portfolios_input_version
        CHECK (analysis_input_version > 0)
);

CREATE UNIQUE INDEX uq_portfolios_one_active_per_owner
    ON portfolios (owner_id)
    WHERE deleted_at IS NULL;

CREATE TABLE companies (
    id                   UUID PRIMARY KEY,
    corp_code            VARCHAR(8) NOT NULL,
    stock_code           VARCHAR(6),
    corp_name            VARCHAR(200) NOT NULL,
    market               VARCHAR(30),
    listed               BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from           DATE,
    valid_to             DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_companies_corp_code UNIQUE (corp_code),
    CONSTRAINT uq_companies_stock_code UNIQUE (stock_code),
    CONSTRAINT ck_companies_corp_code
        CHECK (corp_code ~ '^[0-9]{8}$'),
    CONSTRAINT ck_companies_stock_code
        CHECK (stock_code IS NULL OR stock_code ~ '^[0-9]{6}$'),
    CONSTRAINT ck_companies_valid_period
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE company_aliases (
    id                   UUID PRIMARY KEY,
    company_id           UUID NOT NULL,
    alias                VARCHAR(200) NOT NULL,
    alias_type           VARCHAR(30) NOT NULL DEFAULT 'OTHER',
    valid_from           DATE,
    valid_to             DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_aliases_company
        FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT uq_company_aliases_alias UNIQUE (company_id, alias),
    CONSTRAINT ck_company_aliases_period
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_company_aliases_alias ON company_aliases (alias);

CREATE TABLE holdings (
    id                      UUID PRIMARY KEY,
    portfolio_id            UUID NOT NULL,
    company_id              UUID NOT NULL,
    weight_percent          NUMERIC(7,4) NOT NULL,
    quantity                NUMERIC(30,8),
    average_price_amount    NUMERIC(30,4),
    average_price_currency  CHAR(3),
    investment_started_on   DATE,
    memo                    VARCHAR(1000),
    version                 BIGINT NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT fk_holdings_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_holdings_company
        FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT ck_holdings_weight
        CHECK (weight_percent > 0 AND weight_percent <= 100),
    CONSTRAINT ck_holdings_quantity
        CHECK (quantity IS NULL OR quantity >= 0),
    CONSTRAINT ck_holdings_average_price
        CHECK (average_price_amount IS NULL OR average_price_amount >= 0),
    CONSTRAINT ck_holdings_average_price_currency
        CHECK (
            (average_price_amount IS NULL AND average_price_currency IS NULL)
            OR
            (average_price_amount IS NOT NULL AND average_price_currency IS NOT NULL)
        ),
    CONSTRAINT ck_holdings_version
        CHECK (version > 0)
);

CREATE UNIQUE INDEX uq_holdings_active_company
    ON holdings (portfolio_id, company_id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_holdings_company ON holdings (company_id);

CREATE TABLE investment_theses (
    id                   UUID PRIMARY KEY,
    holding_id           UUID NOT NULL,
    current_version_id   UUID,
    active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT fk_investment_theses_holding
        FOREIGN KEY (holding_id) REFERENCES holdings (id) ON DELETE CASCADE
);

CREATE TABLE investment_thesis_versions (
    id                        UUID PRIMARY KEY,
    thesis_id                 UUID NOT NULL,
    version_no                INTEGER NOT NULL,
    original_text             VARCHAR(1000) NOT NULL,
    topic                     VARCHAR(300),
    expected_direction        VARCHAR(50),
    metrics                   JSONB NOT NULL DEFAULT '[]'::jsonb,
    structure_status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    structure_failure_reason  VARCHAR(100),
    source                    VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_thesis_versions_thesis
        FOREIGN KEY (thesis_id) REFERENCES investment_theses (id) ON DELETE CASCADE,
    CONSTRAINT uq_thesis_versions_number UNIQUE (thesis_id, version_no),
    CONSTRAINT ck_thesis_versions_number
        CHECK (version_no > 0),
    CONSTRAINT ck_thesis_versions_text
        CHECK (char_length(btrim(original_text)) BETWEEN 1 AND 1000),
    CONSTRAINT ck_thesis_versions_metrics
        CHECK (jsonb_typeof(metrics) = 'array'),
    CONSTRAINT ck_thesis_versions_structure_status
        CHECK (structure_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_thesis_versions_source
        CHECK (source IN ('USER', 'MODEL', 'SYSTEM'))
);

ALTER TABLE investment_theses
    ADD CONSTRAINT fk_investment_theses_current_version
    FOREIGN KEY (current_version_id)
    REFERENCES investment_thesis_versions (id)
    ON DELETE SET NULL;

CREATE INDEX ix_theses_holding_active
    ON investment_theses (holding_id, active)
    WHERE deleted_at IS NULL;

CREATE TABLE disclosures (
    id                   UUID PRIMARY KEY,
    receipt_no           VARCHAR(14) NOT NULL,
    company_id           UUID NOT NULL,
    disclosure_type_code VARCHAR(64) NOT NULL,
    report_name          VARCHAR(500) NOT NULL,
    submitted_at         TIMESTAMPTZ NOT NULL,
    submitter            VARCHAR(200),
    correction           BOOLEAN NOT NULL DEFAULT FALSE,
    source_provider      VARCHAR(50) NOT NULL,
    source_url           TEXT,
    fetched_at           TIMESTAMPTZ NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_disclosures_receipt_no UNIQUE (receipt_no),
    CONSTRAINT fk_disclosures_company
        FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_disclosures_type
        FOREIGN KEY (disclosure_type_code) REFERENCES disclosure_types (code),
    CONSTRAINT ck_disclosures_receipt_no
        CHECK (receipt_no ~ '^[0-9]{14}$')
);

CREATE INDEX ix_disclosures_company_submitted
    ON disclosures (company_id, submitted_at DESC);

CREATE INDEX ix_disclosures_type_submitted
    ON disclosures (disclosure_type_code, submitted_at DESC);

CREATE TABLE disclosure_documents (
    id                   UUID PRIMARY KEY,
    disclosure_id        UUID NOT NULL,
    version_no           INTEGER NOT NULL,
    document_role        VARCHAR(30) NOT NULL DEFAULT 'PRIMARY',
    storage_path         TEXT,
    source_url           TEXT,
    content_hash         CHAR(64) NOT NULL,
    media_type           VARCHAR(100),
    fetched_at           TIMESTAMPTZ NOT NULL,
    is_current           BOOLEAN NOT NULL DEFAULT TRUE,
    fetch_status         VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    failure_reason       VARCHAR(100),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disclosure_documents_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT uq_disclosure_documents_version
        UNIQUE (disclosure_id, document_role, version_no),
    CONSTRAINT ck_disclosure_documents_version
        CHECK (version_no > 0),
    CONSTRAINT ck_disclosure_documents_hash
        CHECK (content_hash ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT ck_disclosure_documents_location
        CHECK (storage_path IS NOT NULL OR source_url IS NOT NULL),
    CONSTRAINT ck_disclosure_documents_status
        CHECK (fetch_status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE UNIQUE INDEX uq_disclosure_documents_current
    ON disclosure_documents (disclosure_id, document_role)
    WHERE is_current;

CREATE TABLE disclosure_relations (
    id                   UUID PRIMARY KEY,
    source_disclosure_id UUID NOT NULL,
    target_disclosure_id UUID NOT NULL,
    relation_type        VARCHAR(30) NOT NULL,
    confidence           NUMERIC(5,4),
    relation_basis       VARCHAR(500),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disclosure_relations_source
        FOREIGN KEY (source_disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_relations_target
        FOREIGN KEY (target_disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT uq_disclosure_relations_pair
        UNIQUE (source_disclosure_id, target_disclosure_id, relation_type),
    CONSTRAINT ck_disclosure_relations_not_self
        CHECK (source_disclosure_id <> target_disclosure_id),
    CONSTRAINT ck_disclosure_relations_type
        CHECK (relation_type IN ('CORRECTS', 'SUPERSEDES', 'RELATED')),
    CONSTRAINT ck_disclosure_relations_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE UNIQUE INDEX uq_disclosure_relations_one_original
    ON disclosure_relations (source_disclosure_id)
    WHERE relation_type = 'CORRECTS';

CREATE TABLE citations (
    id                     UUID PRIMARY KEY,
    disclosure_id          UUID NOT NULL,
    disclosure_document_id UUID,
    citation_key           VARCHAR(100) NOT NULL,
    document_title         VARCHAR(500),
    section                VARCHAR(500),
    field_label            VARCHAR(300),
    evidence_text          TEXT NOT NULL,
    evidence_location      VARCHAR(500),
    start_offset           INTEGER,
    end_offset             INTEGER,
    source_url             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_citations_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT fk_citations_document
        FOREIGN KEY (disclosure_document_id) REFERENCES disclosure_documents (id) ON DELETE SET NULL,
    CONSTRAINT uq_citations_key UNIQUE (disclosure_id, citation_key),
    CONSTRAINT ck_citations_offsets
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR
            (start_offset IS NOT NULL AND end_offset IS NOT NULL
             AND start_offset >= 0 AND end_offset >= start_offset)
        )
);

CREATE TABLE disclosure_facts (
    id                     UUID PRIMARY KEY,
    disclosure_id          UUID NOT NULL,
    disclosure_document_id UUID,
    fact_key               VARCHAR(150) NOT NULL,
    field_name             VARCHAR(150) NOT NULL,
    label                  VARCHAR(300) NOT NULL,
    value_type             VARCHAR(20) NOT NULL,
    raw_value              TEXT,
    numeric_value          NUMERIC(38,10),
    date_value             DATE,
    text_value             TEXT,
    boolean_value          BOOLEAN,
    json_value             JSONB,
    currency               CHAR(3),
    unit                   VARCHAR(50),
    period_start           DATE,
    period_end             DATE,
    period_label           VARCHAR(100),
    accounting_basis       VARCHAR(20),
    source_type            VARCHAR(50) NOT NULL,
    extractor_version      VARCHAR(100) NOT NULL,
    extracted_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disclosure_facts_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_facts_document
        FOREIGN KEY (disclosure_document_id) REFERENCES disclosure_documents (id) ON DELETE SET NULL,
    CONSTRAINT uq_disclosure_facts_key
        UNIQUE (disclosure_id, fact_key, extractor_version),
    CONSTRAINT ck_disclosure_facts_value_type
        CHECK (value_type IN ('MONEY', 'NUMBER', 'PERCENT', 'DATE', 'TEXT', 'BOOLEAN', 'JSON')),
    CONSTRAINT ck_disclosure_facts_has_value
        CHECK (
            raw_value IS NOT NULL
            OR numeric_value IS NOT NULL
            OR date_value IS NOT NULL
            OR text_value IS NOT NULL
            OR boolean_value IS NOT NULL
            OR json_value IS NOT NULL
        ),
    CONSTRAINT ck_disclosure_facts_period
        CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
    CONSTRAINT ck_disclosure_facts_accounting_basis
        CHECK (accounting_basis IS NULL OR accounting_basis IN ('CONSOLIDATED', 'SEPARATE', 'NOT_APPLICABLE'))
);

CREATE INDEX ix_disclosure_facts_field
    ON disclosure_facts (disclosure_id, field_name);

CREATE TABLE disclosure_fact_citations (
    fact_id              UUID NOT NULL,
    citation_id          UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (fact_id, citation_id),
    CONSTRAINT fk_disclosure_fact_citations_fact
        FOREIGN KEY (fact_id) REFERENCES disclosure_facts (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_fact_citations_citation
        FOREIGN KEY (citation_id) REFERENCES citations (id) ON DELETE CASCADE
);

CREATE TABLE disclosure_comparisons (
    id                       UUID PRIMARY KEY,
    original_disclosure_id   UUID NOT NULL,
    corrected_disclosure_id  UUID NOT NULL,
    extractor_version        VARCHAR(100) NOT NULL,
    original_document_hash   CHAR(64) NOT NULL,
    corrected_document_hash  CHAR(64) NOT NULL,
    status                   VARCHAR(20) NOT NULL,
    data_as_of               TIMESTAMPTZ NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disclosure_comparisons_original
        FOREIGN KEY (original_disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_comparisons_corrected
        FOREIGN KEY (corrected_disclosure_id) REFERENCES disclosures (id) ON DELETE CASCADE,
    CONSTRAINT uq_disclosure_comparisons_input
        UNIQUE (
            original_disclosure_id,
            corrected_disclosure_id,
            extractor_version,
            original_document_hash,
            corrected_document_hash
        ),
    CONSTRAINT ck_disclosure_comparisons_not_self
        CHECK (original_disclosure_id <> corrected_disclosure_id),
    CONSTRAINT ck_disclosure_comparisons_status
        CHECK (status IN ('COMPLETED', 'PARTIAL', 'FAILED'))
);

CREATE TABLE disclosure_changes (
    id                       UUID PRIMARY KEY,
    comparison_id            UUID NOT NULL,
    field_name               VARCHAR(150) NOT NULL,
    label                    VARCHAR(300) NOT NULL,
    value_type               VARCHAR(20) NOT NULL,
    before_fact_id           UUID,
    after_fact_id            UUID,
    absolute_change          NUMERIC(38,10),
    change_rate_percent      NUMERIC(20,8),
    date_shift_days          INTEGER,
    human_readable           VARCHAR(500),
    formula                  VARCHAR(500),
    change_reason            TEXT,
    display_order            INTEGER NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disclosure_changes_comparison
        FOREIGN KEY (comparison_id) REFERENCES disclosure_comparisons (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_changes_before_fact
        FOREIGN KEY (before_fact_id) REFERENCES disclosure_facts (id) ON DELETE SET NULL,
    CONSTRAINT fk_disclosure_changes_after_fact
        FOREIGN KEY (after_fact_id) REFERENCES disclosure_facts (id) ON DELETE SET NULL,
    CONSTRAINT uq_disclosure_changes_field
        UNIQUE (comparison_id, field_name),
    CONSTRAINT ck_disclosure_changes_value_type
        CHECK (value_type IN ('MONEY', 'NUMBER', 'PERCENT', 'DATE', 'TEXT', 'BOOLEAN', 'JSON')),
    CONSTRAINT ck_disclosure_changes_order
        CHECK (display_order >= 0)
);

CREATE TABLE importance_rules (
    id                       UUID PRIMARY KEY,
    version_code             VARCHAR(100) NOT NULL,
    factor_weights           JSONB NOT NULL,
    level_thresholds         JSONB NOT NULL,
    disclosure_type_scores   JSONB NOT NULL,
    active                   BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from           TIMESTAMPTZ NOT NULL,
    effective_to             TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_importance_rules_version UNIQUE (version_code),
    CONSTRAINT ck_importance_rules_weights
        CHECK (jsonb_typeof(factor_weights) = 'object'),
    CONSTRAINT ck_importance_rules_thresholds
        CHECK (jsonb_typeof(level_thresholds) = 'object'),
    CONSTRAINT ck_importance_rules_type_scores
        CHECK (jsonb_typeof(disclosure_type_scores) = 'object'),
    CONSTRAINT ck_importance_rules_period
        CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE UNIQUE INDEX uq_importance_rules_one_active
    ON importance_rules ((TRUE))
    WHERE active;

CREATE TABLE disclosure_analyses (
    id                       UUID PRIMARY KEY,
    portfolio_id             UUID NOT NULL,
    disclosure_id            UUID NOT NULL,
    comparison_id            UUID,
    importance_rule_id       UUID NOT NULL,
    input_fingerprint        CHAR(64) NOT NULL,
    status                   VARCHAR(20) NOT NULL,
    progress_step            VARCHAR(100),
    completed_steps          INTEGER,
    total_steps              INTEGER,
    importance_score         INTEGER,
    importance_level         VARCHAR(20),
    headline                 TEXT,
    reasons                  JSONB NOT NULL DEFAULT '[]'::jsonb,
    missing_factors          JSONB NOT NULL DEFAULT '[]'::jsonb,
    limitations              JSONB NOT NULL DEFAULT '[]'::jsonb,
    result_json              JSONB,
    document_hash            CHAR(64) NOT NULL,
    portfolio_input_version  BIGINT NOT NULL,
    model_version            VARCHAR(100),
    prompt_version           VARCHAR(100),
    extractor_version        VARCHAR(100) NOT NULL,
    schema_version           VARCHAR(100) NOT NULL,
    requested_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at               TIMESTAMPTZ,
    generated_at             TIMESTAMPTZ,
    data_as_of               TIMESTAMPTZ,
    failure_code             VARCHAR(100),
    failure_message          TEXT,
    CONSTRAINT fk_disclosure_analyses_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_analyses_disclosure
        FOREIGN KEY (disclosure_id) REFERENCES disclosures (id) ON DELETE RESTRICT,
    CONSTRAINT fk_disclosure_analyses_comparison
        FOREIGN KEY (comparison_id) REFERENCES disclosure_comparisons (id) ON DELETE SET NULL,
    CONSTRAINT fk_disclosure_analyses_rule
        FOREIGN KEY (importance_rule_id) REFERENCES importance_rules (id) ON DELETE RESTRICT,
    CONSTRAINT uq_disclosure_analyses_input
        UNIQUE (portfolio_id, disclosure_id, input_fingerprint),
    CONSTRAINT ck_disclosure_analyses_fingerprint
        CHECK (input_fingerprint ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT ck_disclosure_analyses_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_disclosure_analyses_progress
        CHECK (
            (completed_steps IS NULL AND total_steps IS NULL)
            OR
            (completed_steps IS NOT NULL AND total_steps IS NOT NULL
             AND completed_steps >= 0 AND total_steps > 0
             AND completed_steps <= total_steps)
        ),
    CONSTRAINT ck_disclosure_analyses_reasons
        CHECK (jsonb_typeof(reasons) = 'array'),
    CONSTRAINT ck_disclosure_analyses_missing_factors
        CHECK (jsonb_typeof(missing_factors) = 'array'),
    CONSTRAINT ck_disclosure_analyses_limitations
        CHECK (jsonb_typeof(limitations) = 'array'),
    CONSTRAINT ck_disclosure_analyses_importance
        CHECK (
            (importance_score IS NULL AND importance_level IS NULL)
            OR
            (importance_score BETWEEN 0 AND 100 AND (
                (importance_score BETWEEN 70 AND 100 AND importance_level = 'URGENT')
                OR (importance_score BETWEEN 40 AND 69 AND importance_level = 'CAUTION')
                OR (importance_score BETWEEN 0 AND 39 AND importance_level = 'REFERENCE')
            ))
        ),
    CONSTRAINT ck_disclosure_analyses_portfolio_version
        CHECK (portfolio_input_version > 0)
);

CREATE INDEX ix_disclosure_analyses_dashboard
    ON disclosure_analyses (portfolio_id, importance_score DESC, generated_at DESC);

CREATE INDEX ix_disclosure_analyses_status
    ON disclosure_analyses (status, requested_at);

CREATE TABLE analysis_score_components (
    analysis_id          UUID NOT NULL,
    factor_code          VARCHAR(50) NOT NULL,
    score                INTEGER NOT NULL,
    max_score            INTEGER NOT NULL,
    missing              BOOLEAN NOT NULL DEFAULT FALSE,
    explanation          VARCHAR(1000),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (analysis_id, factor_code),
    CONSTRAINT fk_analysis_score_components_analysis
        FOREIGN KEY (analysis_id) REFERENCES disclosure_analyses (id) ON DELETE CASCADE,
    CONSTRAINT ck_analysis_score_components_factor
        CHECK (
            factor_code IN (
                'HOLDING_WEIGHT',
                'DISCLOSURE_TYPE',
                'FINANCIAL_MAGNITUDE',
                'THESIS_RELEVANCE',
                'CORRECTION_REPEAT',
                'FINANCIAL_VULNERABILITY'
            )
        ),
    CONSTRAINT ck_analysis_score_components_range
        CHECK (max_score > 0 AND score >= 0 AND score <= max_score)
);

CREATE TABLE analysis_citations (
    analysis_id          UUID NOT NULL,
    citation_id          UUID NOT NULL,
    citation_role        VARCHAR(30) NOT NULL DEFAULT 'SUPPORTING',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (analysis_id, citation_id),
    CONSTRAINT fk_analysis_citations_analysis
        FOREIGN KEY (analysis_id) REFERENCES disclosure_analyses (id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_citations_citation
        FOREIGN KEY (citation_id) REFERENCES citations (id) ON DELETE RESTRICT,
    CONSTRAINT ck_analysis_citations_role
        CHECK (citation_role IN ('FACT', 'CHANGE', 'INTERPRETATION', 'SUPPORTING'))
);

CREATE TABLE thesis_impacts (
    id                     UUID PRIMARY KEY,
    analysis_id            UUID NOT NULL,
    thesis_version_id      UUID,
    thesis_text_snapshot   VARCHAR(1000) NOT NULL,
    impact_status          VARCHAR(40) NOT NULL,
    summary                TEXT NOT NULL,
    impact_path            TEXT,
    counterpoint           TEXT NOT NULL,
    uncertainty            TEXT NOT NULL,
    confidence             NUMERIC(5,4),
    display_order          INTEGER NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_thesis_impacts_analysis
        FOREIGN KEY (analysis_id) REFERENCES disclosure_analyses (id) ON DELETE CASCADE,
    CONSTRAINT fk_thesis_impacts_version
        FOREIGN KEY (thesis_version_id) REFERENCES investment_thesis_versions (id) ON DELETE SET NULL,
    CONSTRAINT ck_thesis_impacts_status
        CHECK (
            impact_status IN (
                'STRENGTHENED_POSSIBLE',
                'MAINTAINED',
                'WEAKENED_POSSIBLE',
                'NOT_DIRECTLY_RELATED',
                'INSUFFICIENT_EVIDENCE'
            )
        ),
    CONSTRAINT ck_thesis_impacts_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_thesis_impacts_order
        CHECK (display_order >= 0)
);

CREATE TABLE thesis_impact_facts (
    thesis_impact_id     UUID NOT NULL,
    fact_id              UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (thesis_impact_id, fact_id),
    CONSTRAINT fk_thesis_impact_facts_impact
        FOREIGN KEY (thesis_impact_id) REFERENCES thesis_impacts (id) ON DELETE CASCADE,
    CONSTRAINT fk_thesis_impact_facts_fact
        FOREIGN KEY (fact_id) REFERENCES disclosure_facts (id) ON DELETE RESTRICT
);

CREATE TABLE thesis_impact_citations (
    thesis_impact_id     UUID NOT NULL,
    citation_id          UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (thesis_impact_id, citation_id),
    CONSTRAINT fk_thesis_impact_citations_impact
        FOREIGN KEY (thesis_impact_id) REFERENCES thesis_impacts (id) ON DELETE CASCADE,
    CONSTRAINT fk_thesis_impact_citations_citation
        FOREIGN KEY (citation_id) REFERENCES citations (id) ON DELETE RESTRICT
);

CREATE TABLE analysis_scenarios (
    id                   UUID PRIMARY KEY,
    analysis_id          UUID NOT NULL,
    scenario_type        VARCHAR(10) NOT NULL,
    description          TEXT NOT NULL,
    conditions           JSONB NOT NULL,
    display_order        INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_scenarios_analysis
        FOREIGN KEY (analysis_id) REFERENCES disclosure_analyses (id) ON DELETE CASCADE,
    CONSTRAINT ck_analysis_scenarios_type
        CHECK (scenario_type IN ('POSITIVE', 'NEGATIVE')),
    CONSTRAINT ck_analysis_scenarios_conditions
        CHECK (jsonb_typeof(conditions) = 'array' AND jsonb_array_length(conditions) > 0),
    CONSTRAINT ck_analysis_scenarios_order
        CHECK (display_order >= 0)
);

CREATE TABLE scenario_citations (
    scenario_id          UUID NOT NULL,
    citation_id          UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (scenario_id, citation_id),
    CONSTRAINT fk_scenario_citations_scenario
        FOREIGN KEY (scenario_id) REFERENCES analysis_scenarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_scenario_citations_citation
        FOREIGN KEY (citation_id) REFERENCES citations (id) ON DELETE RESTRICT
);

CREATE TABLE next_metrics (
    id                   UUID PRIMARY KEY,
    analysis_id          UUID NOT NULL,
    name                 VARCHAR(300) NOT NULL,
    reason               TEXT NOT NULL,
    availability         VARCHAR(30) NOT NULL,
    expected_source      VARCHAR(500),
    display_order        INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_next_metrics_analysis
        FOREIGN KEY (analysis_id) REFERENCES disclosure_analyses (id) ON DELETE CASCADE,
    CONSTRAINT ck_next_metrics_availability
        CHECK (availability IN ('AVAILABLE', 'PARTIAL', 'NOT_AVAILABLE', 'UNKNOWN')),
    CONSTRAINT ck_next_metrics_order
        CHECK (display_order >= 0)
);

CREATE TABLE conversations (
    id                   UUID PRIMARY KEY,
    owner_id             UUID NOT NULL,
    portfolio_id         UUID NOT NULL,
    title                VARCHAR(300),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at           TIMESTAMPTZ,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT fk_conversations_owner
        FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversations_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE TABLE agent_requests (
    id                       UUID PRIMARY KEY,
    answer_request_id        VARCHAR(100) NOT NULL,
    trace_request_id         VARCHAR(100) NOT NULL,
    owner_id                 UUID NOT NULL,
    portfolio_id             UUID NOT NULL,
    conversation_id          UUID,
    selected_holding_id      UUID,
    selected_disclosure_id   UUID,
    scope                    VARCHAR(20) NOT NULL,
    query                    VARCHAR(2000) NOT NULL,
    status                   VARCHAR(40) NOT NULL,
    answer                   TEXT,
    portfolio_relevance      TEXT,
    clarification_question   TEXT,
    uncertainties            JSONB NOT NULL DEFAULT '[]'::jsonb,
    clarification_candidates JSONB NOT NULL DEFAULT '[]'::jsonb,
    tools_used               JSONB NOT NULL DEFAULT '[]'::jsonb,
    suggested_questions      JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence               NUMERIC(5,4),
    latency_ms               BIGINT,
    model_version            VARCHAR(100),
    prompt_version           VARCHAR(100),
    error_code               VARCHAR(100),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at             TIMESTAMPTZ,
    CONSTRAINT uq_agent_requests_answer_request UNIQUE (answer_request_id),
    CONSTRAINT uq_agent_requests_trace_request UNIQUE (trace_request_id),
    CONSTRAINT fk_agent_requests_owner
        FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_requests_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_requests_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL,
    CONSTRAINT fk_agent_requests_holding
        FOREIGN KEY (selected_holding_id) REFERENCES holdings (id) ON DELETE SET NULL,
    CONSTRAINT fk_agent_requests_disclosure
        FOREIGN KEY (selected_disclosure_id) REFERENCES disclosures (id) ON DELETE SET NULL,
    CONSTRAINT ck_agent_requests_scope
        CHECK (scope IN ('PORTFOLIO', 'HOLDING', 'DISCLOSURE')),
    CONSTRAINT ck_agent_requests_scope_context
        CHECK (
            (scope = 'PORTFOLIO')
            OR (scope = 'HOLDING' AND selected_holding_id IS NOT NULL)
            OR (scope = 'DISCLOSURE' AND selected_disclosure_id IS NOT NULL)
        ),
    CONSTRAINT ck_agent_requests_query
        CHECK (char_length(btrim(query)) BETWEEN 1 AND 2000),
    CONSTRAINT ck_agent_requests_status
        CHECK (
            status IN (
                'PENDING',
                'PROCESSING',
                'SUCCESS',
                'CLARIFICATION_REQUIRED',
                'PARTIAL',
                'UNSUPPORTED',
                'INSUFFICIENT_EVIDENCE',
                'FAILED'
            )
        ),
    CONSTRAINT ck_agent_requests_json_arrays
        CHECK (
            jsonb_typeof(uncertainties) = 'array'
            AND jsonb_typeof(clarification_candidates) = 'array'
            AND jsonb_typeof(tools_used) = 'array'
            AND jsonb_typeof(suggested_questions) = 'array'
        ),
    CONSTRAINT ck_agent_requests_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_agent_requests_latency
        CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX ix_agent_requests_conversation
    ON agent_requests (conversation_id, created_at);

CREATE INDEX ix_agent_requests_owner_created
    ON agent_requests (owner_id, created_at DESC);

CREATE TABLE answer_claims (
    id                   UUID PRIMARY KEY,
    agent_request_id     UUID NOT NULL,
    claim_text           TEXT NOT NULL,
    calculation          JSONB,
    display_order        INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_answer_claims_request
        FOREIGN KEY (agent_request_id) REFERENCES agent_requests (id) ON DELETE CASCADE,
    CONSTRAINT ck_answer_claims_calculation
        CHECK (calculation IS NULL OR jsonb_typeof(calculation) = 'object'),
    CONSTRAINT ck_answer_claims_order
        CHECK (display_order >= 0)
);

CREATE TABLE answer_claim_citations (
    answer_claim_id      UUID NOT NULL,
    citation_id          UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (answer_claim_id, citation_id),
    CONSTRAINT fk_answer_claim_citations_claim
        FOREIGN KEY (answer_claim_id) REFERENCES answer_claims (id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_claim_citations_citation
        FOREIGN KEY (citation_id) REFERENCES citations (id) ON DELETE RESTRICT
);

CREATE TABLE disclosure_sync_jobs (
    id                         UUID PRIMARY KEY,
    portfolio_id               UUID NOT NULL,
    idempotency_key            VARCHAR(200) NOT NULL,
    source_provider            VARCHAR(50) NOT NULL,
    requested_from             DATE NOT NULL,
    requested_to               DATE NOT NULL,
    status                     VARCHAR(20) NOT NULL,
    company_count              INTEGER NOT NULL DEFAULT 0,
    fetched_disclosure_count   INTEGER NOT NULL DEFAULT 0,
    created_disclosure_count   INTEGER NOT NULL DEFAULT 0,
    updated_disclosure_count   INTEGER NOT NULL DEFAULT 0,
    failed_disclosure_count    INTEGER NOT NULL DEFAULT 0,
    failures                   JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at                 TIMESTAMPTZ,
    completed_at               TIMESTAMPTZ,
    CONSTRAINT uq_disclosure_sync_jobs_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_disclosure_sync_jobs_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT ck_disclosure_sync_jobs_period
        CHECK (requested_to >= requested_from),
    CONSTRAINT ck_disclosure_sync_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_disclosure_sync_jobs_counts
        CHECK (
            company_count >= 0
            AND fetched_disclosure_count >= 0
            AND created_disclosure_count >= 0
            AND updated_disclosure_count >= 0
            AND failed_disclosure_count >= 0
        ),
    CONSTRAINT ck_disclosure_sync_jobs_failures
        CHECK (jsonb_typeof(failures) = 'array')
);

CREATE INDEX ix_disclosure_sync_jobs_status
    ON disclosure_sync_jobs (status, created_at);

COMMENT ON TABLE owners IS
    '인증 방식과 무관한 소유 주체. MVP에서는 DEMO_SESSION을 사용하고 로그인 결정 후 USER를 연결한다.';
COMMENT ON TABLE portfolios IS
    'MVP는 owner당 활성 포트폴리오 1개를 부분 유니크 인덱스로 보장한다.';
COMMENT ON COLUMN portfolios.analysis_input_version IS
    '보유 비중 또는 투자 가정 변경 시 증가시키는 분석 캐시 입력 버전.';
COMMENT ON TABLE holdings IS
    '전체 비중 100 이하 규칙은 여러 행을 합산해야 하므로 서비스 트랜잭션에서 잠금과 함께 검증한다.';
COMMENT ON TABLE investment_thesis_versions IS
    '사용자 원문과 구조화 결과를 버전별로 보존한다.';
COMMENT ON TABLE disclosure_documents IS
    '공시 원문 위치와 해시를 보존한다. 원문 내용 자체는 외부 객체 저장소에 둘 수 있다.';
COMMENT ON TABLE disclosure_facts IS
    '공시 원문에서 확인된 사실만 저장한다. 해석 결과는 disclosure_analyses 하위 테이블에 저장한다.';
COMMENT ON TABLE citations IS
    '공시 원문 근거의 재사용 가능한 위치와 텍스트. 사실·분석·답변 주장은 연결 테이블로 참조한다.';
COMMENT ON TABLE disclosure_comparisons IS
    '원공시와 정정공시 비교 결과의 버전된 헤더.';
COMMENT ON TABLE disclosure_analyses IS
    'portfolio와 disclosure 조합에 대한 불변 분석 스냅샷. input_fingerprint가 캐시 키 역할을 한다.';
COMMENT ON TABLE importance_rules IS
    '백엔드 결정적 중요도 계산 규칙. 변경 시 새 version_code 행을 추가한다.';
COMMENT ON TABLE agent_requests IS
    'HTTP trace requestId와 사용자 답변 식별자 answerRequestId를 분리 저장한다.';

INSERT INTO disclosure_types (code, display_name, supported) VALUES
    ('CAPITAL_INCREASE_PAID', '유상증자', TRUE),
    ('CAPITAL_INCREASE_BONUS', '무상증자', TRUE),
    ('CONVERTIBLE_BOND', '전환사채', TRUE),
    ('BOND_WITH_WARRANT', '신주인수권부사채', TRUE),
    ('FACILITY_INVESTMENT', '신규시설투자', TRUE),
    ('SUPPLY_CONTRACT', '단일판매·공급계약', TRUE),
    ('DIVIDEND', '배당', TRUE),
    ('MAJOR_SHAREHOLDER_CHANGE', '최대주주 변경', TRUE),
    ('EMBEZZLEMENT_BREACH_OF_TRUST', '횡령·배임', TRUE),
    ('TRADING_SUSPENSION', '거래정지', TRUE),
    ('EARNINGS_PRELIMINARY', '영업실적·잠정실적', TRUE),
    ('UNSUPPORTED', '미지원 공시', FALSE);

INSERT INTO importance_rules (
    id,
    version_code,
    factor_weights,
    level_thresholds,
    disclosure_type_scores,
    active,
    effective_from
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'importance-v1',
    '{
      "HOLDING_WEIGHT": 35,
      "DISCLOSURE_TYPE": 30,
      "FINANCIAL_MAGNITUDE": 15,
      "THESIS_RELEVANCE": 10,
      "CORRECTION_REPEAT": 5,
      "FINANCIAL_VULNERABILITY": 5
    }'::jsonb,
    '{
      "URGENT": {"min": 70, "max": 100},
      "CAUTION": {"min": 40, "max": 69},
      "REFERENCE": {"min": 0, "max": 39}
    }'::jsonb,
    '{}'::jsonb,
    TRUE,
    TIMESTAMPTZ '2026-07-23 00:00:00+09'
);
